---
- name: Install Memcached
  ansible.builtin.apt:
    name: memcached
    state: present
    update_cache: yes
  become: true

- name: Start and enable Memcached
  ansible.builtin.service:
    name: memcached
    state: started
    enabled: yes
  become: true

- name: Remove any existing bind-address lines
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    regexp: '^-l\s+'
    state: absent
  become: true

- name: Add bind-address to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/memcached.conf
    line: '-l 0.0.0.0'
    insertafter: EOF
  become: true
  notify: restart memcached