---
- name: Fetch RabbitMQ secrets from AWS Secrets Manager
  set_fact:
    rmq_pass: "{{ (lookup('amazon.aws.secretsmanager_secret', 'dev/vprofile/rabbitmq', region=region) | from_json).rmq_pass }}"
    rmq_user: "{{ (lookup('amazon.aws.secretsmanager_secret', 'dev/vprofile/rabbitmq', region=region) | from_json).rmq_user }}"

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes
  become: true

- name: Add RabbitMQ official repository
  ansible.builtin.shell: |
    curl -1sLf "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | gpg --dearmor | sudo tee /usr/share/keyrings/rabbitmq-archive-keyring.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/rabbitmq-archive-keyring.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/rabbitmq.list
    apt-get update -q
  args:
    creates: /etc/apt/sources.list.d/rabbitmq.list
  become: true

- name: Install RabbitMQ server
  ansible.builtin.apt:
    name: rabbitmq-server
    state: present
  become: true

- name: Start and enable RabbitMQ
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes
  become: true

- name: Allow RabbitMQ to accept non-localhost connections
  ansible.builtin.copy:
    content: |
      [{rabbit, [{loopback_users, []}]}].
    dest: /etc/rabbitmq/rabbitmq.config
    mode: '0644'
  become: true
  notify: restart rabbitmq # call handler to restart RabbitMQ after config change
#note : Even though RabbitMQ listens on 0.0.0.0, only Tomcat instances can connect to it. This provides multi-layered security 

- name: Create RabbitMQ application user
  community.rabbitmq.rabbitmq_user:
    user: "{{ rmq_user }}"
    password: "{{ rmq_pass }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  become: true

- name: Enable RabbitMQ management plugin
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  become: true
  notify: restart rabbitmq
