---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ region }}"
    state: "{{ state }}"
    dns_support: true
    dns_hostnames: true
    tenancy: default
    tags:
      Name: "{{ vpc_name }}"
      Environment: "{{ env }}"
      ManagedBy: ansible
  register: vpc_out

- name: Create public subnets
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_out.vpc.id }}"
    cidr: "{{ item.cidr }}" #each item in the list of public_subnets
    az: "{{ item.az }}"
    region: "{{ region }}"
    map_public: true
    tags:
      Name: "{{ item.name }}"
      Type: public
  loop: "{{ public_subnets }}"
  register: pubsub_out

- name: Create private subnets
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_out.vpc.id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ region }}"
    map_public: false
    tags:
      Name: "{{ item.name }}"
      Type: private
  loop: "{{ private_subnets }}"
  register: privsub_out