name: Build and Upload Artifacts to S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR from vprofile repo
        run: |
          git clone https://github.com/devopshydclub/vprofile-project.git /tmp/vprofile-repo
          cd /tmp/vprofile-repo
          mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload WAR to S3
        run: |
          aws s3 cp /tmp/vprofile-repo/target/vprofile-v2.war s3://vprofile-artifacts-12345/ROOT.war

      - name: Upload SQL dump to S3
        run: |
          aws s3 cp /tmp/vprofile-repo/src/main/resources/db_backup.sql s3://vprofile-artifacts-12345/db_backup.sql